FROM node:16.3.0-alpine
WORKDIR /app
COPY ./package.json ./
RUN npm i
ARG PORT
ENV PORT $PORT
ARG DB_URL
ENV DB_URL $DB_URL
ARG BUCKET_NAME
ENV BUCKET_NAME $BUCKET_NAME
ARG ACCOUNT_ID
ENV ACCOUNT_ID $ACCOUNT_ID
ARG SECRET_ACCESS_KEY
ENV SECRET_ACCESS_KEY $SECRET_ACCESS_KEY
ARG ACCESS_KEY_ID
ENV ACCESS_KEY_ID $ACCESS_KEY_ID
COPY . .
CMD ["npm","start"]